// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feed_followers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFeedFollowers = `-- name: CreateFeedFollowers :one
INSERT INTO feed_followers (id, created_at, updated_at, user_id, feed_id)
VALUES ($1, DEFAULT, DEFAULT, $2, $3)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFeedFollowersParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) CreateFeedFollowers(ctx context.Context, arg CreateFeedFollowersParams) (FeedFollower, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollowers, arg.ID, arg.UserID, arg.FeedID)
	var i FeedFollower
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
